### PR TITLE
fix: Avoid TypeError for null values on CUSTOM_ELEMENT_HANDLING config.

### PR DESCRIPTION
**Pull request by cpmotion**
ISSUE-897

## Summary

[See issue](https://github.com/cure53/DOMPurify/issues/897). Change made in utils and test added.

## Tasks

Not sure if there's a better way to inverse assert in the test. Please advise if so. Tested locally to pass and fail. It "works" but kind of a workaround for QUnit it seems...

### CODE REVIEW

**Comment by cpmotion** [comment]
Just realized saving in test-suite applied prettier fixes. I guess prettier is not running in pipeline to validate against config. Hmm, I'm going to undo those lines for this specific commit and update pr..

**Comment by cure53** [comment]
This is great, thanks you!

**Comment by cpmotion** [comment]
@cure53 any chance we could push a patch(3.0.8) out asap? We have a specific scenario where we're picking up latest v3 and that would really help a currently deployed product version. Thank you!

**Comment by cure53** [comment]
This release should fix it: https://github.com/cure53/DOMPurify/releases/tag/3.0.8

**Comment by cpmotion** [comment]
Awesome thanks!

**Pull request merged**
