### PR TITLE
RETURN_DOM_FRAGMENT and RETURN_DOM_IMPORT

### LINKED ISSUE #62: Option to return a DocumentFragment instead of html
The way I am currently using dompurify looks like this:

```javascript
var html = this.databaseEntity.foo;
html = dompurify(this.document.defaultView).sanitize(html);
var fragment = parseHTMLSnippit(this.document.defaultView, html);
this.bar.appendChild(fragment);
```

Which means the html is being parsed twice. It would be useful if there was an option in dompurify to return a DocumentFragment. (adopted/imported into the document dompurify has been constructed with). 

For example:

```javascript
var html = this.databaseEntity.foo;
var fragment = dompurify(this.document.defaultView).sanitize(html, {output: 'fragment'});
this.bar.appendChild(fragment);
```

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
Fixes #62

Should work properly even if `SANITIZE_DOM` is disabled.

```javascript
document.body.appendChild(
    DOMPurify.sanitize(dirty, {RETURN_DOM_FRAGMENT: true, RETURN_DOM_IMPORT: true})
);
```

### CODE REVIEW

**Comment by cure53** [comment]
Looks good to me, just checked the commits. 

@fhemberger @neilj What do you think?

**Comment by Joris-van-der-Wel** [comment]
> OK. I can't see how the past names map might be used to compromise security at the moment, but I agree it's better just to use importNode and not worry about it. Might be nice to have a comment in the source code explaining why it was chosen; helps people coming in later (and indeed ourselves in a few months…).

> OK for the options too; I take your point on consistency.

I have added a comment https://github.com/Joris-van-der-Wel/DOMPurify/commit/5618f47feb36766e83a4bab4a8f3388ca1fab463#diff-9d220e0bdde67c89de82589b198242ccR630

**Comment by Joris-van-der-Wel** [comment]
Rebased

**Comment by cure53** [comment]
I am happy with the code and ready for a merge. Any objections for now?

**Comment by neilj** [comment]
Looks good to me with the latest changes. :+1: 

(Sorry for the delay; GitHub didn't email me with the latest comment for some reason).

**Comment by cure53** [comment]
Thank you and no worries :)

**Pull request merged**
