### PR TITLE
switched custom element handling to an object defining three differen…

### LINKED ISSUE #601: Followup for #596: Preserve all attributes on autonomous custom elements
This is a followup for #596. Background see that issue.

### Bug

Given we configure DOMPurify with `{ ALLOWED_CUSTOM_ELEMENTS: /^foo-/ }`, it must preserve any attributes and attribute values on those matching custom elements.

#### Input

`<foo-bar baz="foobar"></foo-bar>`

#### Given output

`<foo-bar></foo-bar>`

#### Expected output

`<foo-bar baz="foobar"></foo-bar>`

### Feature

Custom elements can implement their own attributes and are free to name them however they like. For these elements to still work, not changing their attributes is essential.

### PR DESCRIPTION
**Pull request by franktopel**
…t properties: tagNameCheck, attributeNameCheck, allowCustomizedBuiltInElements

> This pull request fixes #601 

### Background & Context

We agreed on [this configuration format](https://github.com/cure53/DOMPurify/pull/602#issuecomment-979044494).

### Dependencies

- [x] no dependencies

### CODE REVIEW

**Comment by franktopel** [comment]
Not sure what is the problem here. Your repo had a `package-lock.json` before:

image

**Comment by cure53** [comment]
LOL, okay - that happens some times, had that before :)

**Comment by cure53** [comment]
This looks good to me, merging now and running some local tests. Thank you :)

**Comment by franktopel** [comment]
Not sure if my tests are sufficient now, please check.

**Pull request merged**
