### PR TITLE
Optimise and refine

### PR DESCRIPTION
**Pull request by neilj**
This pull request encompasses the following refinements:
1. Optimise: without changing the semantics, many easy optimisations were made, for example changing from searching an array for allowed tags/attributes [O(n)] to constructing a lookup table [O(1)].
2. Fix small documentation errors, typos and whitespace inconsistencies.
3. Add an "isSupported" property to the DOMPurify object to allow users to easily check if the browser supports the full DOMPurify.
4. Fix a bug where sanitize would return a string even when RETURN_DOM is set, if the input had no "<" character.
5. Always return the full html including browser inferred `<html><body>` etc. tags if WHOLE_DOCUMENT config option is set, even if the input has no "<" character.

The test suite has one modification for (5). No other semantic changes were made and the full test suite runs without error in latest Chrome.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Can you add a test for the `RETURN_DOM` change?

**Comment by neilj** [comment]
Sure, no problem. Done.

**Comment by fhemberger** [comment]
Cool, thank you!

**Comment by mathiasbynens** [comment]
Also please add a test that checks if the `isSupported` property is present (so we don’t accidentally remove/rename it in the future). Thanks!

**Comment by neilj** [comment]
Sure, done.

**Comment by mathiasbynens** [comment]
@neilj

**Comment by cure53** [comment]
Thanks, @neilj! That was a lot of work and very good changes. Very much appreciated. 

I am currently reviewing if the changes introduced any security regressions (specifically on MSIE). Once done, I am ready to merge. Should be the case by around tomorrow.

**Comment by neilj** [comment]
Thanks @cure53; code review is definitely important in a project like this! I'm looking into using DOMPurify as an extra layer of defence in the [FastMail](https://www.fastmail.com) web UI, so I was more than happy to spend a few hours this morning tidying it up as I read through and understood the code.

**Comment by cure53** [comment]
@neilj Fully agreed, and if you don't mind, I would like to add your name to the acknowledgements section in the README.md. In case all is fine on MSIE10+ as well (cannot test right now, am on the road), I will probably trigger a new release tomorrow as well. Thanks again :)

**Comment by neilj** [comment]
Sure, that would be great. Thanks.

**Comment by cure53** [comment]
Tests are working well on IE10+, FF and Spartan. I am ready for a merge. The change-review was successful as well - no objections from my side. 

Any objections, @fhemberger and @mathiasbynens?

**Comment by fhemberger** [comment]
LGTM :+1:

**Comment by mathiasbynens** [comment]
Belated LGTM :+1: (https://github.com/cure53/DOMPurify/pull/52#issuecomment-89962686 already implied it, kinda)

**Pull request merged**
