### PR TITLE
Bump browsers versions to support for…of and let/const

### PR DESCRIPTION
**Pull request by buzinas**
## Summary

Potential fix for #785.

## Background & Context

Bump browsers versions in order to remove a lot of polyfills for `for…of` and `const/let`.

### CODE REVIEW

**Comment by cure53** [comment]
Something seems to break the tests, not sure if related.

https://github.com/cure53/DOMPurify/actions/runs/4536381460/jobs/8000156773#step:7:31

**Comment by buzinas** [comment]
I'll take a look, thanks!

**Comment by buzinas** [comment]
@cure53 the reason tests were failing was due to all target browsers now supporting ESM and then Babel keeping the ES Modules untouched. By removing the `commonjs` plugin, `expect.js` started failing since it was using `module.exports`.

I tried to update it to `export default` instead, which fixed browser tests with Karma, but this change broke JSDOM tests, since they run on NodeJS. Then I converted it to UMD (similar to test-suite.js) and started using `window.tests` on ESM, and although it worked, this felt too hacky.

So I finally renamed `expect.js` to `expect.mjs` and dynamically imported it on `jsdom-node.js`. In order to be able to do that, I had to wrap the code into an async function (since non-modules can't have top-level `await`).

Now all tests work as expected! Please let me know what you think.

**Comment by cure53** [comment]
Fantastic, thank you :smile:

**Pull request merged**
