### PR TITLE
Add setup and adjustments for karma tests via BrowserStack.

### PR DESCRIPTION
**Pull request by tdeekens**
> This pull request adds support for running the old QUnit test suite via Karma against BrowserStack's Selenium hub via TravisCI.

## Changes made

1. Add necessary Karma dependencies
- Add jQuery as bower dependency to be injected into browsers
- Import `purify.js` via webpack (it won't expose itself otherwise as `module` is defined in Karma
- Move `epect.json` to `expect.js` to simplify loading and don't require parsing it as JSON 
- Move test suite from `index.html` to `purify.spec.js`
- Add `travis.yml` with encrypted credentials for BrowserStack
- Add Browsers as custom launchers in `karma.conf.js`

## Todo pre-merge

1. Contact BrowserStack to give free access (they thankfully give free automated testing to Open Source projects mentioning them in `readme.md`
- Add TravisCI hook to trigger build upon push 
- Fix bug in IE11: [DOMPurifyr Sanitization test[mXSS Variation I] FAILED](https://travis-ci.org/tdeekens/DOMPurify/builds/80644260)

```text
Payload: <listing>&lt;img onerror="alert(1);//" src=1&gt;<t t></listing>
Expected: &lt;img onerror="alert(1);//" src=1&gt;
Actual: <img src="1">
```

## Todo post-merge

1. Update BrowserStack credentials using Travis gem (`travis encrypt`)

I am happy to help with any of the required steps as far as I can without being a collaborator on the base fork.

### CODE REVIEW

**Comment by cure53** [comment]
Heya!

Wow, that is awesome :D Thanks!

Now, there is one minor issue: The failing test on MSIE11 *only* happens on unpatched IE11. Once IE11 is at latest patch level, that bug should not appear any much longer because they fixed that behaviour of `<listing>` auto-decoding its contents in one of the patch-Tuesdays.

I would suggest to fix that via `assert.contains` if no one objects.

**Comment by cure53** [comment]
@tdeekens I added that variation to the tests, does it work now?

**Comment by cure53** [comment]
@tdeekens I also contacted BrowserStack w.r.t. a free open source account. Let's see what they will say, once I have an answer I will post here again. Don't see why we wouldn't get one :)

**Comment by tdeekens** [comment]
:star2: Yay :tada: 

[TOTAL: 2245 SUCCESS](https://travis-ci.org/tdeekens/DOMPurify/builds/80657583).

So that's done. You wanna add specific browsers to test against or does the current set satisfy you for now?

BrowserStack usually answers within a day - won't hurt to mention them in your readme already to speed up the process. A quick shoutout like 

```text
Thanks to [BrowserStack](https://browserstack.com) for supporting this project with their services for free!
```

will do.

**Comment by cure53** [comment]
We're getting an account, just got feedback. Sweet :)
I'll set everything up tomorrow - thanks for all the work!

**Pull request merged**
