### PR TITLE
Refactor `getGlobal` to not cause CSP warnings

### PR DESCRIPTION
**Pull request by tdeekens**
### Background & Context

This relates to #249.

Please critically reflect the old UMD interaction with the `factory` as in https://github.com/cure53/DOMPurify/blob/a992d3a75031cb8bb032e5ea8399ba972bdf9a65/src/purify.js#L1-L16 was there before I worked on the library.

Locally JSDOM and Karma against Chrome works fine.

### CODE REVIEW

**Comment by frigus02** [comment]
Thanks for the nearly immediate response. You are amazingly fast.

Maybe just don't see it. But did you actually include and use `root.js` now?

**Comment by tdeekens** [comment]
No, we can't use `window-or-root` for reasons stated in #249.

1. It falls back to `this` on a top level which rollup will replace to `undefined` due to https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
2. It's not really working as stated in the docs and does not have an ESM build

The "real" change is https://github.com/cure53/DOMPurify/pull/250/files#diff-39d3e4cf739c51697e855107d73a23f5R5. However, I am not 100% sure if that covers all semantics/needs towards a `getRoot` for the library and an older maintainer should answer.

**Comment by tdeekens** [comment]
A now I see your point. Sorry `root.js` was a left over from experimenting. Now removed.

**Comment by cure53** [comment]
Aaaand merging!

**Pull request merged**
