### PR TITLE
See #230

### PR DESCRIPTION
**Pull request by ydaniv**

### CODE REVIEW

**Comment by cure53** [comment]
Looking good but no tests. Cannot accept the PR without :)

**Comment by ydaniv** [comment]
Hmmm... will do. But notice it's failing on `lint`. It's weird, since I didn't pass it at first and couldn't commit, on stuff in `purify.js`, which I didn't touch, and then ran `format`, passed `lint` and pushed. And now, I don't the CI is breaking on the same rules in lint.

**Comment by ydaniv** [comment]
So, added 1 test, which I think covers it 😕 
But still failing on that discrepancy in lint config.

**Comment by tdeekens** [comment]
Sounds like conflicting prettier and eslint versions or rules due to unpinned dependencies maybe. Sorry for the inconvienence. Just code on and I'll check things as soon as I find time.

**Comment by tdeekens** [comment]
Just reminded myself that I added yarn to this project. The lockfile should pin everything. Did you install dependencies via yarn? We might have to add an npm-shrinkwrap or lockfile while deciding on what npm version we want to support.

**Comment by ydaniv** [comment]
npm. a note on the README would be nice 😃

**Comment by tdeekens** [comment]
Sure. @ydaniv what do you think of #235. Would that have clarified things for you?

**Comment by cure53** [comment]
Also, https://github.com/cure53/DOMPurify/commit/2dd0206cb74a70dc567d251ff1143154ea85f5e8 :)

**Comment by cure53** [comment]
Something seems wonky @tdeekens 

https://travis-ci.org/cure53/DOMPurify/jobs/253332077

**Pull request merged**
