### PR TITLE
Run tests using jsdom on travis and the local-test script

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
Also see #149 

Perhaps you could push this branch as a branch on cure53/DOMPurify to make sure that travis succeeds? This PR will of course also trigger a travis run, but without the karma tests.

### CODE REVIEW

**Comment by Joris-van-der-Wel** [comment]
Here's a PR build: https://travis-ci.org/cure53/DOMPurify/builds/127449379

**Comment by cure53** [comment]
Awesome, checking now!

**Comment by cure53** [comment]
All looks fine, thanks a ton :D 

That is one major addition - and I think we are now pretty much ready for 0.8.

**Comment by Joris-van-der-Wel** [comment]
cool!

**Pull request merged**
