### PR TITLE
feat: add NAMESPACE config

### LINKED ISSUE #533: svg elements that not contained in <svg> been removed after 2.2.6
> This issue proposes a bug which...

### Background & Context

I use DOMPurify to sanitize innerHTML of \<g> element

#### Input

```javascript
DOMPurify.sanitize('<polyline points="0 0"></polyline>', { USE_PROFILES: { svg: true } })
```

#### Given output

2.2.4: `<polyline points="0 0"></polyline>`

2.2.6: empty string

#### Expected output

same as 2.2.4

maybe related to #495, but i can not find a option to specify root namespace.

### PR DESCRIPTION
**Pull request by NateScarlet**
for sanitize svg/mathML child innerHTML

resolve #533

> This pull request implements namespace config to allow user provide parent namespace

### Background & Context

mXSS protection added in #495 removed the ability to sanitize svg/mathML fragment.

Need a option to re-enable them.

### Tasks

lint error before i made the change:
```
src\purify.js:799:29
  ‼  799:29  Function has a complexity of 23. Maximum allowed is 20.  complexity
```

### CODE REVIEW

**Comment by cure53** [comment]
This looks very sexy, let me review this today, thank you :)

**Comment by NateScarlet** [comment]
https://github.com/cure53/DOMPurify/blob/0bc97869eb208b8632b15f54facb961e978455b1/src/purify.js#L708
this change cause error in firefox

**Comment by cure53** [comment]
Yeah, I am fine with this side effect for now.

**Comment by cure53** [comment]
Oof, the tests are green and now even MSIE is happy. Somewhat :D

**Comment by cure53** [comment]
Thank you for this PR! Much appreciated.

**Pull request merged**
