### PR TITLE
Update _isClobbered to check currently required properties

### PR DESCRIPTION
**Pull request by neilj**
The _isClobbered fn detects whether any of the methods/attributes we need on
the element have been clobbered. The properties it checks for had not been
updated with the changes in how the sanitisation methods manipulated the
elements, meaning it was making some unnecessary checks, and not making some
required ones, which could result in an error being thrown with certain input.

### CODE REVIEW

**Comment by Joris-van-der-Wel** [comment]
This breaks in jsdom (although this is jsdom's fault) https://github.com/tmpvar/jsdom/issues/1136 #29

```javascript
doc.createElement('div').attributes.toString() // '[object Object]' in jsdom`
```

**Comment by Joris-van-der-Wel** [comment]
Actually, this is not fixable in jsdom until new ES6 features land in iojs

**Comment by cure53** [comment]
Ew, I see. You would requite `Symbol.toStringTag()` I assume? 
Can we work around that or should we revert?

**Comment by neilj** [comment]
We could just change it to just use `attributes.toString()`, then it's fixable without ES6. I don't *think* this is a security risk (someone please double check you can't clobber to toString property of the clobbered attributes property).

This is then easily shimmable.

I've done this in commit 486f155.

**Comment by Joris-van-der-Wel** [comment]
Using instanceof should also work:

```javascript
var document = require('jsdom').jsdom()
var window = document.defaultView;

var purifyDoc = document.implementation.createHTMLDocument();
purifyDoc.createElement('div').attributes instanceof window.NamedNodeMap === true
```

**Comment by Joris-van-der-Wel** [comment]
Yes, it would require `attributes[Symbol.toStringTag] = ...`

**Comment by neilj** [comment]
Oh, good call. Yes, that's a much better solution.

**Comment by cure53** [comment]
I think the `instanceof` approach is a bit risky. I am currently testing with this example:

```html
<form onclick=alert(attributes)>
clickme (expecting somthing else)
<input name=attributes>
<input name=attributes>
</form>

<form onclick=alert(attributes)>
clickme (expecting a NamedNodeMap)
<input name=bla>
<input name=blubb>
</form>
```

In current Gecko and Blink we get a `[object RadioNodeList]`, in MSIE11 and 10 we get `[object HTMLCollection]` and I am not sure if it's really impossible to clobber it to become a named node map. We had one bypass like that in the past - so I am a bit anxious here ;)

**Comment by neilj** [comment]
I'm fairly sure it's not possible to clobber it into a NamedNodeMap. It's certainly still strictly more secure than what we had before my previous patch that you just landed. The old test was:

    (elm.attributes instanceof HTMLCollection) ||
    (elm.attributes instanceof NodeList) ||
    typeof elm.attributes.item !== 'function'

If you could have clobbered it to be a NamedNodeMap, it would have passed all these tests!

I've done pull request #66 if you're happy to land the change.

**Comment by cure53** [comment]
LGTM!

**Comment by Joris-van-der-Wel** [comment]
Also, it appears that in firefox 22 it was named `MozNamedAttrMap`. So this would affect both the instanceof and toString() solutions.

**Comment by neilj** [comment]
Yeh, just reading that: it was changed back in FF34. Let's get the constructor directly from the browser: see pull request #67. (Note, I don't have an old FF to test with and my internet connection at the moment is too slow to download it, so I'd appreciate someone double checking this works in all browsers first! It certainly works in the current Chrome/Safari/FF/Opera and Opera 12).

**Comment by Joris-van-der-Wel** [comment]
Hah. should set up testem + saucie or (something similar) for this kind of stuff.

**Comment by neilj** [comment]
Bah, no that doesn't work (see the comment in #67). If someone can download FF22, I have another idea that should work:

    var NamedNodeMap = window.NamedNodeMap || window.MozNamedAttrMap;

I'm not sure if NamedNodeMap is still defined in FF22 though (even though it's not used for attributes). If it is, we need to switch the order:
    
    var NamedNodeMap = window.MozNamedAttrMap || window.NamedNodeMap;

I think that should work.

**Comment by Joris-van-der-Wel** [comment]
Here's another questionable solution:
```
Object.getPrototypeOf(document.body.attributes) === Object.getPrototypeOf(document.createElement('form').attributes)
```

**Comment by cure53** [comment]
I think I prefer @neilj's approach here. We can clobber the prefixed version though in newer FF (and all other browsers):

```html
<form id="MozNamedNodeMap"></form>
<script>alert(MozNamedNodeMap)</script>
```

**Comment by Joris-van-der-Wel** [comment]
I tried this in Firefox 22 Linux:

```html
<!DOCTYPE html>
<html>
	<head><title>DOMPurify temporary stuff</title></head>
	<body>
		<p>foo</p>
		<p><script>var NamedNodeMap = window.NamedNodeMap || window.MozNamedAttrMap;
		document.write(document.body.attributes.toString());
		document.write(document.body.attributes instanceof NamedNodeMap);
		</script></p>
		<p><script>document.write(Object.getPrototypeOf(document.body.attributes) === 
				Object.getPrototypeOf(document.createElement('form').attributes)
		);</script></p>
		<p>bar</p>
	</body>
</html>

```

Result: https://saucelabs.com/jobs/48fbfec372704992922c8f3fc7ff71e5/0002screenshot.png

**Comment by neilj** [comment]
@cure53 I don't think the clobbering of NamedNodeMap or MozNamedAttrMap matters, because we cache our reference to it when purify.js is first evaluated, (presumably) before we pass in any malicious content, so before any clobbering can take place. The clobbering will overwrite the global var, but we already have a local var with a reference.

@Joris-van-der-Wel I'm curious to double check: is window.NamedNodeMap defined in FF22? If so, we don't need to change anything (because it's already supporting backwards compatibility). Otherwise, it looks like my patch will work fine.

**Comment by cure53** [comment]
@neilj You are right!

**Comment by Joris-van-der-Wel** [comment]
@neilj It is __not__ defined. Also its typeof MozNamedAttrMap is "object", while typeof "NamedNodeMap" is "function"

**Comment by neilj** [comment]
OK, so this patch is good:

    var NamedNodeMap = window.NamedNodeMap || window.MozNamedAttrMap;

Made pull request #70.

**Pull request merged**
