### PR TITLE
Fix DOMPurify.removed for SAFE_FOR_JQUERY mode

### PR DESCRIPTION
**Pull request by dnkolegov**
Additional check in `SAFE_FOR_JQUERY` mode was deleted in `0.8.1` version. As result `DOMPurify.removed` contained elements even if input data is valid. I have restored one and added some new tests.

### CODE REVIEW

**Comment by cure53** [comment]
Yeah, I had to remove the check yesterday, because it broke too many tests and the security fix had priority. I will review the PR later today.

**Comment by cure53** [comment]
Alright, looking good :) Thanks - and sorry for the hiccups. We had to address the security issue yesterday with highest prio - and this one fell under the table.

**Comment by dnkolegov** [comment]
Cool. Thanks. Our internal tests  for `DOMPurify` in waf mode are successful.

**Comment by cure53** [comment]
:+1:

**Pull request merged**
