### PR TITLE
Refactor library to support ES201* JavaScript

### LINKED ISSUE #202: [Suggestion]: Adding webpack to allow ES201* JavaScript
> This issue proposes a feature which adds webpack as a build tool.

### Background & Context

Currently DOMPurity does not have a built tool in place. This is nice and often simplifies things. However, adding webpack might give the project some benefits and this issue is about to align on the potential gain of it.

### Feature

Adding webpack would yield the following benefits

- Simpler modularisation of code (constants, config and logic)
- Writing more "modern" JS with ES201*
- Removes the "clutter" for universal JS at the beginning of `src/purify.js`
   - Webpack adds this to the dist
- Removes "custom" minification as webpack has different "targets"
   - Uses Uglify too

Adding webpack might have the following disadvantages

- A built tool always adds complexity in mental overhead and approachability to a project
- The test setup needs to be adjusted to consume a dist file

What do you all think? Might this be worth to at least spin up a PR for and discuss progress along the way or is it something DOMPurify does not really need? I would be able to drive the change...

### PR DESCRIPTION
**Pull request by tdeekens**
> This adds rollup as a build tool and relates to issue #202.

### Background & Context

Currently DOMPurity does not have a built tool in place. This is nice and often simplifies things. However, adding webpack might give the project some benefits and this issue is about to align on the potential gain of it.

This PR might change quite a couple of things and can/should be seen as a start of a discussion on how far to go with things.

1. Change in API with more granular exports (not "just" the object) e.g. sanitize and
   - to allow `import sanitize, { addHook } from 'purify'` 

### Included in this

1. Adding webpack with configuration for umd build
2. Removing jshint replacing it with xo
   - to allow ES201x syntax to be linted with a default set of sane eslint rules
3. Refactors some code to illustrate potential in changes
   - Some files where put into separate modules
   - Other changes fix linting errors while others add exceptions
4. Rewires jsdom to test built version of purify

### Open complications

1. Mode detection (running in browser or node)
   - exports are static and early return won't do (?) which breaks script parsing in node

I tried to split up changes into sensible commits to be "easier" to digest. I hope it worked. 

closes #202

### CODE REVIEW

**Comment by cure53** [comment]
Heya, is this already ready for merging?

**Comment by tdeekens** [comment]
No no. I was more waiting for some input. Agreement and potentially disagreements. I can continue working on it as soon as I have time whenever the general path is agreed with kina ☺️.

**Comment by tdeekens** [comment]
@cure53 Alright, progress. The build passes again and all tooling, apart from the webpack vs. rollup debate, is in place. Next up I will have to rebase/merge with master. Which is gonna be a bit of hand picking 🐱 .

**Comment by tdeekens** [comment]
Any feedback so far on this? Any preference on webpack vs. rollup?

**Comment by cure53** [comment]
Sorry, I honestly have no idea about these things and rely on review-input from @fhemberger and @neilj :) My feedback here is as worthless as it can be.

**Comment by tdeekens** [comment]
No worries. I just rebased all changes over `master` and fixed remaining issues. I hope the commit history makes sense to review. Would love to hear thoughts from the other contributors.

**Comment by tdeekens** [comment]
Alright, rebased again on top of `master` to get changes from version `0.9.0` in. I'll now replace 'webpack' with 'rollup'. Any feedback so far?

**Comment by fhemberger** [comment]
@tdeekens Sorry, I haven't worked with webpack or rollup so far, so I can't asses this PR.

**Comment by tdeekens** [comment]
No worries. I'll have a friend very familiar with it look over it maybe to give some "trust indication"?

**Comment by tdeekens** [comment]
...so karma now also runs using rollup and some other improvements have been made.

**Comment by cure53** [comment]
I finally managed to read the code, shall we give it a try? :D Or not yet merge ready?

**Comment by tdeekens** [comment]
Nothing much to add from my side. Give me the weekend to look over things one last time and maybe update our jsdom testing to jsdom@10.

I'll ping you once I am certain all is good. 🎈

**Comment by tdeekens** [comment]
@cure53. From my side this is ready to go in. Anything you'd like addressed before hitting the button?

**Comment by luhmann** [comment]
I took a look at this as requested by @tdeekens and ran the cross-browser test-suite against the configured browsers as well as the most recent versions of Firefox, Chrome, Safari and Edge.

The tests are fine except for IE Edge 15, where this test seems to be consistently failing: https://github.com/tdeekens/DOMPurify/blob/refactoring/es2016/test/test-suite.js#L36

Output
```
Expected: [
	  "<a data-·._=\"foo\" href=\"#\">abc</a>",
	  "<a href=\"#\">abc</a>"
	]
	Actual: "<a href=\"#\" data-·._=\"foo\">abc</a>"
	   at Anonymous function (node_modules/qunitjs/qunit/qunit.js:2194:4)
	   at QUnit.assert.contains (test/config/setup.js:13:3)
	   at Anonymous function (test/purify.spec.js:977:9)
	   at runTest (node_modules/qunitjs/qunit/qunit.js:843:4)
	   at Test.prototype.run (node_modules/qunitjs/qunit/qunit.js:828:4)
	   at Anonymous function (node_modules/qunitjs/qunit/qunit.js:970:6)
```
But if I read the comment next to the test correctly, that seems to be expected. So don't know if there is any issue here.

Besides that I only found two minor issues:
1. The karma test-config is not executable as is because there is a typo in https://github.com/tdeekens/DOMPurify/blob/refactoring/es2016/test/karma.conf.js#L73, the browser is named `bs_yosemite_safari_9`, but further down in the same file it is referenced as `bs_yosemite_safari_8`, the latter is correct for the intended configuration.
2. There is one remaining reference to Webpack in `README.md` under `Development and contributing`

Wasn't in the mood to create a PR for things that small .. sorry 😉

Apart from that the setup looks fine to me and the application code at least looks sane. Cannot comment on functionality per se, but the tests are passing so we should be fine.

I would have one suggestion for improvement, which would be to also run the test-suite in mobile browsers as that is a feasible use-case for the library and possible with Browserstack. But I do not know if you want to support that.

**Comment by tdeekens** [comment]
Thanks bud. I'll take care of the two minor issues. The failing test is something @cure53 should comment on.

**Comment by tdeekens** [comment]
The last two commits address the issues mentioned. Leaves us with:

1. IE Edge 15 not working - is that the case on `master` too?
2. The question if we should test mobile - probably not part of this PR

Thanks everyone!

**Comment by cure53** [comment]
> The failing test is something @cure53 should comment on.

Good catch, fixed it :D

**Comment by tdeekens** [comment]
Did you fix the yosemite typo only - as I did here too - or also the failing test? 😅

**Comment by cure53** [comment]
Only fixed the typo so far. 
 
> `Actual: "<a href=\"#\" data-·._=\"foo\">abc</a>"`

This looks safe to me. MSIE/Edge often change attribute orders. This can be added to the expectations array without risk as far as I can see.

**Comment by tdeekens** [comment]
Do you mind adding it? I'll then resolve conflicts here and we can get this in?

**Comment by cure53** [comment]
Done :)

**Comment by tdeekens** [comment]
Alright @cure53 clean rebase, clean merge? Merge whenever you feel like it.

**Comment by cure53** [comment]
@tdeekens Looks like the browser tests are failing now, maybe I did sth wrong?

https://travis-ci.org/cure53/DOMPurify/jobs/235933656

**Comment by tdeekens** [comment]
Oh shot. I will look into it. I ran karma locally before and thought we ran againat BrowserStack too. Can only be some configuration.

**Comment by tdeekens** [comment]
I just ran the karma tests locally and they pass. I also ran FF52 and IE10 against my personal BrowserStack account and they pass. I am bit confused by why the failed after the merge. The error indicates that our setup is not transpiled correctly. I'll try to find out why.

**Comment by cure53** [comment]
Yeah looks like it, thx :)

**Pull request merged**
