### PR TITLE
Fix #1033

### LINKED ISSUE #1033: Small syntax enhancement to TMPLIT_EXPR
> This issue proposes a small enhancement to the regexp in the `TMPLIT_EXPR` const.

### Background & Context

`const TMPLIT_EXPR = seal(/\${[\w\W]*}/gm);`

Projects that use XSLT can inline 3rd party libs before pushing out the response to the browser. While doing so they can perform code resolution/substitutions on ${} espressions. Unfortunately the `${[\w\W]*}` part can be misinterpreted as an expression even though it's in a regexp, and because it obviously doesn't resolve to anything during the transformation, it gets wiped out as a result and causes a syntax error when the browser gets it.
Result: `const TMPLIT_EXPR = seal(/\/gm);`

### Proposed workaround

The solution is extremely simple and doesn't change anything to how the regexp operates, and would improve compatibility with a wider range of mission critical projects build on "older" tech like XSLT.
All that is needed is to escape the first curly brace like so:
`const TMPLIT_EXPR = seal(/\$\{[\w\W]*}/gm);`

Would you like me to create a PR for this?

### PR DESCRIPTION
**Pull request by svdb99**
## Summary

Small fix for issue #1033 

## Background & Context

`const TMPLIT_EXPR = seal(/\${[\w\W]*}/gm);`

Projects that use XSLT can inline 3rd party libs before pushing out the response to the browser. While doing so they can perform code resolution/substitutions on ${} espressions. Unfortunately the `${[\w\W]*}` part can be misinterpreted as an expression even though it's in a regexp, and because it obviously doesn't resolve to anything during the transformation, it gets wiped out as a result and causes a syntax error when the browser gets it.
Result: `const TMPLIT_EXPR = seal(/\/gm);`

## Proposed solution

The solution is extremely simple and doesn't change anything to how the regexp operates as it merely escapes the first curly brace.

### CODE REVIEW

**Comment by svdb99** [comment]
The Lint error wants to optimize the regexp by removing the escape character I added.
Well, no. This "optimization" is precisely what caused the issue in the first place.

**Comment by cure53** [comment]
Feel free to silence it with a eslint-disable :D

**Comment by cure53** [comment]
We are planning a release later today, are you planning to get this change in and amend the PR? :)

**Comment by svdb99** [comment]
Done.

**Comment by svdb99** [comment]
What's your time zone? I'm in CET (UTC+1)

**Comment by cure53** [comment]
Awesome, thanks :slightly_smiling_face:

**Comment by cure53** [comment]
> What's your time zone? I'm in CET (UTC+1)

Same

**Comment by cure53** [comment]
This is again breaking the tests and we have already invested a lot off useless effort into adding one character, I would really recommend that you don't blindly commit stuff but actually run the linter before.

The comment you want to add is this: `// eslint-disable-line unicorn/better-regex`

**Comment by cure53** [comment]
Thanks, this looks better and tests don't die on init this time. In case all good, we will merge and then  release 3.2.2

**Comment by svdb99** [comment]
Sorry, I'm a security analyst not a software developer nor lint expert, and I'm not allowed to install any of your tools on my laptop, so I did indeed copy the same comment from the next line assuming it would be the same. I usually only test new library versions for security breaches and upgrade them in our products when needed (we use over 1800 different libraries). But for DomPurify it was impossible due to this single character.
Thank you for your understanding.

**Comment by cure53** [comment]
No worries, we managed after all :slightly_smiling_face:

**Pull request merged**
