### PR TITLE
Fix and update setup of tests

### PR DESCRIPTION
**Pull request by tdeekens**
> This pull request tries to fix the setup of the tests.

### Background & Context

1. Adds `BABEL_ENV` to `test:ci`
2. Adds `cross-env` to `test`
3. Moves testing on BrowserStack to node@6

Please try to run BS tests locally by e.g. tweaking the npm run-script in the `package.json` to

```diff
- "test:ci": "cross-env NODE_ENV=test BABEL_ENV=rollup npm run lint && npm run test:jsdom && (([ \"${TRAVIS_PULL_REQUEST}\" != \"false\" ] || [ \"${TEST_BROWSERSTACK}\" != \"true\" ]) || karma start test/karma.conf.js --log-level error --reporters dots --single-run)",
+ "test:ci": "cross-env NODE_ENV=test BABEL_ENV=rollup BS_USERNAME=xxx BS_ACCESSKEY=yyy karma start test/karma.conf.js --log-level error --reporters dots --single-run)",
```

### CODE REVIEW

**Comment by tdeekens** [comment]
I've got trouble reproducing tests failing for the same reasons as after merging #206.

1. Locally against Chrome passes and the non transpiled `require` which throws on BS is transpiled when debugging the launched instance
2. Running the tests against BS also works  without getting the exception from the `require`

Ok, you merged while I was typing this 🗡

**Comment by cure53** [comment]
Oops, it sounded doneish :D

**Comment by tdeekens** [comment]
Sorry for not being clear enough :). Can you try run against BS locally to reproduce the error? I fail so far.

**Comment by cure53** [comment]
Locally things work

**Pull request merged**
