### PR TITLE
Adds automatic minification as pre-commit and tests minified version

### PR DESCRIPTION
**Pull request by tdeekens**
:tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip::tulip:

> Consider this a pull request for discussion to which changes can be made...

# Changes in this pull request

- Adds a `karma-mocha-reporter` for more readable log output
- Refactor test suite into separate file which is included in `purify.spec.js` and `purify.min.spec.js`
  - The only way I was able to convince QUnit to run all parameterized tests
- Add a pre-commit hook using [npm package](https://github.com/observing/pre-commit) performing minification and running tests
  - Minified sources will be amended to commit (`HEAD`)
  - Arguable if all tests should run on every commit still `--no-verify` omits hooks but also minification

:hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus::hibiscus:

### CODE REVIEW

**Comment by tdeekens** [comment]
...not building due to overusing BrowserStack I guess. Let's wait a day.

**Comment by cure53** [comment]
Heya, should we try again and see if it builds?

**Comment by tdeekens** [comment]
Sure. You can retrigher the build on TraviaCI with a very small button 😇

**Comment by cure53** [comment]
Hmm, something is still broken - and it's not the request limit:

```
19 09 2015 15:10:19.311:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
BrowserStackTunnel: binary not present
19 09 2015 15:10:19.335:WARN [launcher]: Can not load "bs_win81_ie_11"!
  Error: Username is required.
```

I think we might have a mismatch with expected exports and the actual data in our `travis.yml`.

**Comment by tdeekens** [comment]
Yeah I've seen that. I removed my old keys from which were left over in the `travis.yml` from #92. I've also refactored things a bit. I hope it builds with only `DOMPurify`'s keys but lets see in a bit.

**Comment by tdeekens** [comment]
I think didn't quite add those keys correctly on `master` cause they are clearly somehow bound to the repo as I can't build with a set of mine. Furthermore, the build does not output a

```bash
Setting environment variables from .travis.yml
$ export BS_USERNAME=[secure]
$ export BS_ACCESSKEY=[secure]
```bash

which it should. 

Should we maybe remove all on `master` and re-add them using `travis encrypt` on the travis-gem? I'll then merge master into this PR and we can see if all things work.

**Comment by cure53** [comment]
The encrypted credentials were added with:
```
travis encrypt BROWSER_STACK_USERNAME=XXX --add env.global
travis encrypt BROWSER_STACK_ACCESS_KEY=XXX --add env.global
```
That might be the problem?

**Comment by tdeekens** [comment]
Yeah, they should be named as [here](https://github.com/cure53/DOMPurify/blob/master/test/karma.conf.js#L24-L25). That's funny cause all BrowserStack builds went over my account - just checked :smile_cat:. Unsure if you need the `env.global` value there.

**Comment by cure53** [comment]
Then this might fix it.. https://github.com/cure53/DOMPurify/commit/fea7c6864c55589f0f31f24885f60097e2272a16

**Comment by cure53** [comment]
Looking good :)

**Comment by tdeekens** [comment]
:sunny: Awsum! Just a thing of taste towards managing pull requests and feature-branches in the future: merging master into the feature-branch (pull request) just before merging back to ensure CI works and get a clean merge-commit is usually the way to go. Still, all just taste as long as things work all is good :smile:. Yay, towards testing all the things!

**Comment by cure53** [comment]
@tdeekens Another stupid question of mine: I just changed the version tags to prepare for 0.7.0. The tests are failing - API overuse. Yet, there is no new dist version in the folder. 

Is there anything I have to do for that?

**Pull request merged**
