### PR TITLE
Option to set config once

### PR DESCRIPTION
**Pull request by jfparadis**
This proposal allows for the setting and clearing of the configuration the DOMPurify instance, similar to add/remove hooks.

Tests will be added if/when this feature solidifies.

### CODE REVIEW

**Comment by cure53** [comment]
Sorry, I wasn't sure - are you gonna add tests in this PR or rather in later ones? :D

**Comment by tdeekens** [comment]
Can't we use the 'CONFIG' object to check if things have been parsed? Sorry for being confused.

**Comment by jfparadis** [comment]
@cure53  Yes, I will add tests prior to requesting a merge. My apologies for the delay. I am currently traveling for a conference.

@tdeekens The add/remove hooks API adds callback that are persistent across multiple sanitize calls until remove is called. The goal here is to add an API to add configuration once, persist it across multiple sanitize calls, and optionally clear it to remove it at a later stage.

**Comment by cure53** [comment]
@jfparadis No worries at all and thx :D

**Comment by cure53** [comment]
Closing this for inactivity

**Pull request closed without merging**
