### PR TITLE
WIP: Test for failing builds

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by fhemberger** [comment]
'push' tests don't run the latest changes (so it fails), but the general PR seems to work.

**Comment by cure53** [comment]
Ready for a merge?

**Comment by fhemberger** [comment]
As you said the last time: The build is already broken ;)

This should hopefully improve a few things, but I think in general the whole Karma/BrowerStack tests are borked. I now re-ran them a couple of times on Travis: Sometimes they pass, sometimes they don't (throwing one or more of: "browserstack binary not installed", "browser.on is not a function", "test caused full page reload", "disconnected", etc).

**Comment by cure53** [comment]
So, what do we do about those?

**Comment by fhemberger** [comment]
Honestly, I don't know right now. As I'm also not the person who set up this testing infrastructure in the first place.

**Comment by cure53** [comment]
@Joris-van-der-Wel and @tdeekens do you have any ideas what could be the breakage here?

**Comment by fhemberger** [comment]
Great, looks we hit BrowserStack's rate limit this time. m(
Is there a more stable service we can use for browser testing?

**Comment by cure53** [comment]
We already got a bigger request limit than usual from them. Unlikely they will give us more (for free).

**Comment by fhemberger** [comment]
As a couple of well-known companies are using DOMPurify, how about asking them for sponsoring our test setup?

**Comment by Joris-van-der-Wel** [comment]
@cure53 Well, the jsdom breakage is fixed for now because the version was reverted to 7. I see that in the travis job log that it goes through the jsdom tests without error now. (note that the build script will not start the karma test if jsdom fails).

Are you sure the error from browserstack is not just it complaining about retrying too fast? Is the DISCONNECTED error not the real error, or is that also caused by the rate limit?

**Comment by tdeekens** [comment]
I've had the same issues in others projects and they don't even always relate to BrowserStack and e.g. SourceLabs won't make our life easier.

> "browserstack binary not installed", "browser.on is not a function"

Are definitely bound to it and I will have a look as soon as I can.

> "test caused full page reload", "disconnected"

Are more rooted in the nature and structure of the test suite imho.

**Pull request merged**
